### ISSUE TITLE
Incompatible with Carpet

### ISSUE THREAD

**Issue by YoMonNPC** [Elikill58/NegativityFabric#2]
Carpet Version: 1.4.101+v230319
Negativity Version: 2.6.1-SNAPSHOT
NegativityFabric Version: 1.2.0-SNAPSHOT

Logs:
With Negativity: https://1drv.ms/u/s!AmrZcoVCJXw0iHklH4_w-qw9tybH?e=0K81SW
Without Negativity: https://1drv.ms/u/s!AmrZcoVCJXw0iHeEM9JDXCnZqBZF?e=t8Bn9Y

**Comment by Elikill58** [comment]
Sorry for the issue. It's not easy to fix, and ...
Duplicate of https://github.com/Elikill58/Negativity/issues/347
