### ISSUE TITLE
Structure 1.19.4 After loading negatively, it does not play an anti-cheat role on the server

### ISSUE THREAD

**Issue by YFlowery** [Elikill58/NegativityFabric#3]
After the negative anti-cheat was loaded normally on the fabric 1.19.4 server, the anti-cheat did not take effect. The negative in-game settings screen can be opened.

**Comment by Elikill58** [comment]
It's because of #4

**Comment by YFlowery** [comment]
You misunderstood, this issue did not occur at the same time as the carpet mod. And 1.19.4 does not start the server at all when installing both negative and carpet mods.

**Comment by Elikill58** [comment]
You mean, without Carpet mod, the server start fine but no cheat are detected ? If yes, please provide mode details as result of /n debug, or come on discord for more help

**Comment by YFlowery** [comment]
![BUG](https://github.com/Elikill58/NegativityFabric/assets/84625184/6f6ec265-252c-4f83-94b6-ec6dbe64eb00)
![QQ图片20230519160338](https://github.com/Elikill58/NegativityFabric/assets/84625184/ce26bc5c-7e00-4111-be3d-cf08298bce47)

**Comment by YFlowery** [comment]
If you put on no OP and do not have any permissions, you can still cheat

**Comment by Elikill58** [comment]
This should be fixed now
