### ISSUE TITLE
The Fabric server's carpet mod does not work with negativity anti-cheat.

### ISSUE THREAD

**Issue by YFlowery** [Elikill58/NegativityFabric#4]
When carpet mods are installed into mods files at the same time as negative, mod conflicts occur, causing server startup failures.

**Comment by YFlowery** [comment]
[latest.log](https://github.com/Elikill58/NegativityFabric/files/11509134/latest.log)

**Comment by Elikill58** [comment]
Fixed as described in https://github.com/Elikill58/NegativityFabric/issues/2
